### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by AngelDez** [akorb/SteamShutdown#22]
Dont know if you are still active but for some reason i have this problem even though it works normally before

Here are the logs :
System.TypeInitializationException: The type initializer for 'SteamShutdown.Steam' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\MyGames\SteamLibrary\SteamApps'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.EnumerateFiles(String searchPattern)
   at SteamShutdown.Steam.UpdateAppInfos()
   at SteamShutdown.Steam..cctor()
   --- End of inner exception stack trace ---
   at SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at SteamShutdown.CustomApplicationContext..ctor()
   at SteamShutdown.Program.Main()

I dont get why the path is G:/ even though i dont have a G:/ partition on my PC, could an external HDD be the problem?

**Comment by akorb** [comment]
Yes, I am still active.

Can you check if the directory in G:\ is added in `Steam Library Folders`?

See https://support.steampowered.com/kb_article.php?ref=7418-YUBN-8129

If yes, remove it. Since you say this drive doesn't even exist.

**Comment by AngelDez** [comment]
Thanks for the quick answer, and no there is no G:\ directory installed on my steam library folders, hence why i am confused why the problem is there in the first place :(

**Comment by akorb** [comment]
Can you post the value of this registry key please:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\InstallPath`

**Comment by akorb** [comment]
Can you check if with the newest release the problem still persists? (if it still happened)
