### ISSUE TITLE
Different crash on startup

### ISSUE THREAD

**Issue by AntonioPedro6** [akorb/SteamShutdown#29]
This one is similiar to #22 but it seems to be for different reasons.

`System.TypeInitializationException: The type initializer for 'SteamShutdown.Steam' threw an exception. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: �. Path '', line 1, position 3.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at SteamShutdown.Steam.FileToAppInfo(String filename)
   at SteamShutdown.Steam.UpdateAppInfos(IEnumerable'1 libraryPaths)
   at SteamShutdown.Steam..cctor()
   --- End of inner exception stack trace ---
   at SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at SteamShutdown.CustomApplicationContext..ctor()
   at SteamShutdown.SteamShutdown.Main()`

That question mark with the diamond shaped background shows up as an empty small square with UTF8 enconding.
Also with W10 x64 with 3 library folders.

Here is the appmanifest file - [https://ufile.io/sdb8civm](https://ufile.io/sdb8civm)

**Comment by akorb** [comment]
Thanks for your report. 

The file you attached works fine for me. Could you please tell me which language your Windows 10 system is set to?

**Comment by akorb** [comment]
Ah and one more question. How do you know it crashes at `appmanifest_228980.acf` file?

**Comment by AntonioPedro6** [comment]
System language is set to English_US and I don't know if it crashed at that file, I sent it just in case it was necessary.

**Comment by akorb** [comment]
Almost one year later, sorry for that
Does that problem still persist?
