### ISSUE TITLE
Crash on startup (v2.3.5)

### ISSUE THREAD

**Issue by troy0h** [akorb/SteamShutdown#39]
```
30/06/2021 23:37:02: System.TypeInitializationException: The type initializer for 'SteamShutdown.Steam' threw an exception. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'ContainsKey'
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at SteamShutdown.Steam.GetLibraryPaths(String installationPath)
   at SteamShutdown.Steam..cctor()
   --- End of inner exception stack trace ---
   at SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at SteamShutdown.CustomApplicationContext..ctor()
   at `SteamShutdown.SteamShutdown.Main()
```
v2.3.4 works fine

**Comment by troy0h** [comment]
Oh, I've just seen that this is already a known issue, ill close this one
