### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by valery-kirichenko** [akorb/SteamShutdown#45]
The app crashes with the following log:
```
07.10.2021 1:21:16: System.TypeInitializationException: The type initializer for 'SteamShutdown.Steam' threw an exception. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: W. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at SteamShutdown.Steam.FileToAppInfo(String filename)
   at SteamShutdown.Steam.UpdateAppInfos(IEnumerable`1 libraryPaths)
   at SteamShutdown.Steam..cctor()
   --- End of inner exception stack trace ---
   at SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at SteamShutdown.CustomApplicationContext..ctor()
   at SteamShutdown.SteamShutdown.Main()
```

**Comment by ShadowDuke** [comment]
Same.

**Comment by akorb** [comment]
Hi, can you still reproduce this error?
If yes, please execute the following version and cause this error to appear.
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/8144289/SteamShutdown.zip)

This will create a file called `debugging.txt` on your desktop. Please share this file with me.
Also, if the last line of this text file says something like:
`<date> <time> FileToAppInfo: <path to an acf file>`
please attach this acf file as well.

**Comment by valery-kirichenko** [comment]
Yeah it was reproducible. Thanks to a debugging.txt I have found multiple corrupted acf files (some of them were binary, others had text content they shouldn't have had), deleted them and the app is now working just fine.

Seems like better handling of such files would be nice

**Comment by akorb** [comment]
Do you have a copy of these  corrupted files?
Would be helpful to pinpoint what went wrong and making the code more
robust. Otherwise I can only guess what went wrong

Valery Kirichenko ***@***.***> schrieb am Fr., 25. Feb. 2022,
23:10:

**Comment by valery-kirichenko** [comment]
[appmanifest.zip](https://github.com/akorb/SteamShutdown/files/8145234/appmanifest.zip)
